In [1]:
print('hi')

hi


In [ ]:
#a
import numpy as np

In [ ]:
#b
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#c
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#d
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#e
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#f
np.arange(10,51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#g
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#h
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#i
np.random.sample()

0.42268678554067896

In [ ]:
#j
np.random.normal(0,1,25)

array([-2.08842022, -0.04642024, -0.08019687,  0.4706258 , -1.34983718,
       -0.51338321,  0.68464736, -1.77748179,  0.2984281 ,  1.14616981,
        0.03004301, -0.3390621 ,  0.7172234 , -0.89744178,  1.88322681,
       -0.09616702, -0.14652076, -1.30142642, -0.23757531,  1.25189201,
        1.16492327,  0.46532892,  0.77179337, -0.02439086, -0.36594733])

In [ ]:
#k
np.linspace(0.01,1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#l
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#m
mat[3,4]

20

In [ ]:
#n
mat[:3,1]

array([ 2,  7, 12])

In [ ]:
#o
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
#p
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#q
mat.sum()

325

In [ ]:
#r
mat.std()

7.211102550927978

In [ ]:
#s
mat.sum(axis=0)

array([55, 60, 65, 70, 75])